services:
  valkey:
    image: valkey/valkey
    ports:
      - 6379:6379
  vector-db:
    image: qdrant/qdrant
    ports:
      - 6333:6333
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
